---
- name: Register new Satellite hosts
  hosts: all
  become: true

  tasks:
  - name: Deploy katello-ca-consumer-latest on Satellite client
    yum:
      name: http://satgm.example.com/pub/katello-ca-consumer-latest.noarch.rpm
      state: present
  
  - name: Execute subscription registration with auto-attach
    redhat_subscription:
      state: present
      org_id: Base
      activationkey: Test Kickstart Key
